# Generated by Django 2.2.dev20180621213648 on 2018-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_persona_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='fotos/imagen1.jpg', upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
